DWH_cloudwatch_uid = "Mention appropriate id here for prod"
BI_cloudwatch_uid  = "Mention appropriate id here for prod"
DWH_Redshift_uid   = "Mention appropriate id here for prod"
BI_Redshift_uid    = "Mention appropriate id here for prod"
DWH_Athena_uid     = "Mention appropriate id here for prod"
BI_Athena_uid      = "Mention appropriate id here for prod"
alert_email        = "prod-alerts@example.com"