version: 2.1

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:1.5.7
    environment:
      TF_IN_AUTOMATION: 1
      TF_INPUT: 0

jobs:
  fmt:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Check Terraform formatting
          command: terraform fmt -check -diff -recursive

  plan:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Start Grafana Container
          command: |
            apk add --no-cache docker-cli
            docker run -d -p 3000:3000 --name=grafana -e GF_SECURITY_ADMIN_PASSWORD=admin grafana/grafana:latest
            sleep 10

      - run:
          command: terraform init
      - run:
          command: terraform validate
      - run:
          command: terraform plan -var-file=dev.tfvars -out=tfplan
      - persist_to_workspace:
          root: .
          paths:
            - tfplan

  apply:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Start Grafana Container
          command: |
            apk add --no-cache docker-cli
            docker run -d -p 3000:3000 --name=grafana -e GF_SECURITY_ADMIN_PASSWORD=admin grafana/grafana:latest
            sleep 10
      - attach_workspace:
          at: .
      - run:
          command: terraform init
      - run:
          command: terraform apply -auto-approve tfplan

workflows:
  terraform:
    jobs:
      - fmt
      - plan:
          requires:
            - fmt
      - approve:
          type: approval
          requires:
            - plan
          filters:
            branches:
              only: 
                - main
                - final10
      - apply:
          requires:
            - approve
          filters:
            branches:
              only:
                - main
                - final10
